// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntpwubtuywlbfvyyszwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cHd1YnR1eXdsYmZ2eXlzendiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MjA5NDksImV4cCI6MjA2ODk5Njk0OX0.bceb7DOZbAAt-r3mHHeMBLdhqKmOvPtNvSHel-v1wF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});